// Dev generator (D65 Slice 0): re-emit src/api/merchant/agreement/agreement-v2-source.ts
// as a verbatim, escape-safe copy of the canonical agreement artifact
//   docs/legal/drafts/merchant-agreement-v2-draft.md
// Run: npx tsx prisma/_gen-agreement-source.ts
//
// The generated module is what the version registry (versions.ts) hashes. Keeping
// this generator in-repo means the embedded copy can be re-derived from the artifact
// deterministically (no hand transcription), and a guard test locks the two together.
// This is NOT wired into the build; it is a one-shot maintenance tool run only when
// the artifact bytes legitimately change (which, by append-never-mutate, means a NEW
// version id, not an edit of a published one).
import fs from 'node:fs'
import crypto from 'node:crypto'
import path from 'node:path'

const ARTIFACT = 'docs/legal/drafts/merchant-agreement-v2-draft.md'
const OUT = 'src/api/merchant/agreement/agreement-v2-source.ts'

const raw = fs.readFileSync(path.resolve(process.cwd(), ARTIFACT), 'utf8')
const hash = crypto.createHash('sha256').update(raw, 'utf8').digest('hex')
const lit = JSON.stringify(raw)

const module = [
  '// AUTO-GENERATED - DO NOT EDIT BY HAND.',
  '//',
  '// Verbatim byte-for-byte copy of the canonical agreement artifact',
  `//   ${ARTIFACT}`,
  '// re-generated by prisma/_gen-agreement-source.ts. Every [SOLICITOR: ...] marker',
  '// and the LEGAL-REVIEW-REQUIRED / DRAFT header are preserved exactly. The version',
  '// registry (versions.ts) hashes THIS string; a guard test asserts this constant',
  '// still equals the on-disk artifact and that sha256(this) equals the pinned hash,',
  '// so a signed evidence record can always be reconstructed and verified.',
  '//',
  `// sha256(canonical source): ${hash}`,
  '',
  `export const MERCHANT_AGREEMENT_V2_SOURCE = ${lit}\n`,
].join('\n')

fs.writeFileSync(path.resolve(process.cwd(), OUT), module)
// eslint-disable-next-line no-console
console.log(`wrote ${OUT}; sha256=${hash} bytes=${Buffer.byteLength(raw, 'utf8')}`)
